import type { SchemaExport, SchemaField } from '../../../models';

export const PULL_MARKER = '// Generated by `localess schema pull`. Do not edit — the next pull overwrites this file.';

/** PascalCase schema id -> kebab-case file base name. */
export function toKebabCase(id: string): string {
  return id.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

/**
 * `multiline` controls whether an array of plain objects (e.g. an enum's `values`) prints one
 * item per line, indented under `indent` — used for top-level schema/enum properties, but not
 * for a field's own properties, which stay on `defineField`'s single line.
 */
function printValue(value: unknown, indent = 2, multiline = true): string {
  if (typeof value === 'string') return quote(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    if (multiline && value.every(isPlainObject)) {
      const itemIndent = ' '.repeat(indent + 2);
      const closeIndent = ' '.repeat(indent);
      const items = value.map(item => `${itemIndent}${printValue(item, indent + 2, multiline)},`);
      return `[\n${items.join('\n')}\n${closeIndent}]`;
    }
    return `[${value.map(item => printValue(item, indent, multiline)).join(', ')}]`;
  }
  if (isPlainObject(value)) {
    const entries = Object.entries(value)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `${k}: ${printValue(v, indent, multiline)}`);
    return `{ ${entries.join(', ')} }`;
  }
  return String(value);
}

// Prettier's own default — a neutral baseline, not this (or any consuming) project's own
// .prettierrc value. Every project pulling schemas has its own preference; `printWidth` is a
// parameter precisely so it never has to match a value hardcoded here.
export const DEFAULT_PRINT_WIDTH = 80;

// Matches the property order the Localess editor UI shows for a field, so a generated
// defineField(...) call reads in the same order regardless of the wire object's own key order.
// `fileTypes` (the plural ASSET/ASSETS restriction) isn't part of the editor's field-detail form
// the rest of this list mirrors, so it's placed right after its singular counterpart rather than
// specified by that UI ordering.
const FIELD_PROPERTY_ORDER = [
  'name',
  'kind',
  'displayName',
  'required',
  'translatable',
  'description',
  'defaultValue',
  'minValue',
  'maxValue',
  'minLength',
  'maxLength',
  'minValues',
  'maxValues',
  'source',
  'schemas',
  'path',
  'fileType',
  'fileTypes',
];

function orderedEntries(field: SchemaField): [string, unknown][] {
  return Object.entries(field)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => {
      const rank = (key: string) => {
        const i = FIELD_PROPERTY_ORDER.indexOf(key);
        return i === -1 ? FIELD_PROPERTY_ORDER.length : i;
      };
      return rank(a) - rank(b);
    });
}

function printFields(fields: SchemaField[], byId: Set<string>, printWidth: number): string {
  const lines = fields.map(field => {
    const entries = orderedEntries(field).map(([key, val]) => {
      if (key === 'source' && typeof val === 'string' && byId.has(val)) return `source: ${val}`;
      if (key === 'schemas' && Array.isArray(val)) {
        const items = val.map(ref => (typeof ref === 'string' && byId.has(ref) ? ref : quote(String(ref))));
        return `schemas: [${items.join(', ')}]`;
      }
      return `${key}: ${printValue(val, 2, false)}`;
    });
    const singleLine = `    defineField({ ${entries.join(', ')} }),`;
    if (singleLine.length <= printWidth) return singleLine;
    const propLines = entries.map(entry => `      ${entry},`).join('\n');
    return `    defineField({\n${propLines}\n    }),`;
  });
  return lines.join('\n');
}

/**
 * Emit one TypeScript definition file per schema plus an index.ts with defineConfig. Each field
 * is wrapped in defineField(...) rather than emitted as a bare object literal, so a hand-edited
 * pulled file still gets defineField's excess-property checking. A defineField call that would
 * exceed `printWidth` wraps to one property per line, matching the pulling project's own
 * formatting preference (not this CLI's). Cross-schema references become imports; ids not present
 * in the pulled set stay strings. Deterministic: same input and printWidth, byte-identical output.
 */
export function emitSchemaFiles(schemas: SchemaExport[], printWidth = DEFAULT_PRINT_WIDTH): Map<string, string> {
  const byId = new Set(schemas.map(schema => schema.id));
  const files = new Map<string, string>();

  for (const schema of schemas) {
    if (schema.type === 'ENUM') {
      const props = Object.entries(schema)
        .filter(([key, val]) => key !== 'id' && key !== 'type' && val !== undefined)
        .map(([key, val]) => `  ${key}: ${printValue(val)},`);
      const body = `export const ${schema.id} = defineEnum({\n  id: ${quote(schema.id)},\n${props.join('\n')}\n});\n`;
      files.set(`${toKebabCase(schema.id)}.ts`, [PULL_MARKER, `import { defineEnum } from '@localess/schema';`, '', body].join('\n'));
      continue;
    }

    const imports = new Set<string>();
    for (const field of schema.fields ?? []) {
      if ('source' in field && typeof field.source === 'string' && byId.has(field.source)) imports.add(field.source);
      if ('schemas' in field && Array.isArray(field.schemas)) {
        for (const ref of field.schemas) if (byId.has(ref)) imports.add(ref);
      }
    }
    imports.delete(schema.id);
    const importLines = [...imports].sort().map(id => `import { ${id} } from './${toKebabCase(id)}';`);
    const headProps = Object.entries(schema)
      .filter(([key, val]) => key !== 'id' && key !== 'fields' && val !== undefined)
      .map(([key, val]) => `  ${key}: ${printValue(val)},`);
    const hasFields = (schema.fields?.length ?? 0) > 0;
    const fieldsBlock = schema.fields ? `  fields: [\n${printFields(schema.fields, byId, printWidth)}\n  ],` : '';
    const body = `export const ${schema.id} = defineSchema({\n  id: ${quote(schema.id)},\n${[...headProps, fieldsBlock].filter(Boolean).join('\n')}\n});\n`;
    const schemaImport = hasFields ? 'defineField, defineSchema' : 'defineSchema';
    files.set(
      `${toKebabCase(schema.id)}.ts`,
      [PULL_MARKER, `import { ${schemaImport} } from '@localess/schema';`, ...importLines, '', body].join('\n')
    );
  }

  const names = schemas.map(schema => schema.id);
  const indexImports = schemas.map(schema => `import { ${schema.id} } from './${toKebabCase(schema.id)}';`);
  files.set(
    'index.ts',
    [
      PULL_MARKER,
      `import { defineConfig } from '@localess/schema';`,
      ...indexImports,
      '',
      `export const config = defineConfig({\n  schemas: [${names.join(', ')}],\n});\n`,
    ].join('\n')
  );
  return files;
}
