import type { SchemaExport, SchemaField } from '../../../models';

export const PULL_MARKER = '// Generated by `localess schema pull`. Do not edit — the next pull overwrites this file.';

/** PascalCase schema id -> kebab-case file base name. */
export function toKebabCase(id: string): string {
  return id.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function printValue(value: unknown): string {
  if (typeof value === 'string') return quote(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) return `[${value.map(item => printValue(item)).join(', ')}]`;
  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `${k}: ${printValue(v)}`);
    return `{ ${entries.join(', ')} }`;
  }
  return String(value);
}

function printFields(fields: SchemaField[], byId: Set<string>): string {
  const lines = fields.map(field => {
    const entries = Object.entries(field)
      .filter(([, v]) => v !== undefined)
      .map(([key, val]) => {
        if (key === 'source' && typeof val === 'string' && byId.has(val)) return `source: ${val}`;
        if (key === 'schemas' && Array.isArray(val)) {
          const items = val.map(ref => (typeof ref === 'string' && byId.has(ref) ? ref : quote(String(ref))));
          return `schemas: [${items.join(', ')}]`;
        }
        return `${key}: ${printValue(val)}`;
      });
    return `    defineField({ ${entries.join(', ')} }),`;
  });
  return lines.join('\n');
}

/**
 * Emit one TypeScript definition file per schema plus an index.ts with defineConfig. Each field
 * is wrapped in defineField(...) rather than emitted as a bare object literal, so a hand-edited
 * pulled file still gets defineField's excess-property checking. Cross-schema references become
 * imports; ids not present in the pulled set stay strings. Deterministic: same input, byte-identical
 * output.
 */
export function emitSchemaFiles(schemas: SchemaExport[]): Map<string, string> {
  const byId = new Set(schemas.map(schema => schema.id));
  const files = new Map<string, string>();

  for (const schema of schemas) {
    if (schema.type === 'ENUM') {
      const props = Object.entries(schema)
        .filter(([key, val]) => key !== 'id' && key !== 'type' && val !== undefined)
        .map(([key, val]) => `  ${key}: ${printValue(val)},`);
      const body = `export const ${schema.id} = defineEnum({\n  id: ${quote(schema.id)},\n${props.join('\n')}\n});\n`;
      files.set(`${toKebabCase(schema.id)}.ts`, [PULL_MARKER, `import { defineEnum } from '@localess/schema';`, '', body].join('\n'));
      continue;
    }

    const imports = new Set<string>();
    for (const field of schema.fields ?? []) {
      if ('source' in field && typeof field.source === 'string' && byId.has(field.source)) imports.add(field.source);
      if ('schemas' in field && Array.isArray(field.schemas)) {
        for (const ref of field.schemas) if (byId.has(ref)) imports.add(ref);
      }
    }
    imports.delete(schema.id);
    const importLines = [...imports].sort().map(id => `import { ${id} } from './${toKebabCase(id)}';`);
    const headProps = Object.entries(schema)
      .filter(([key, val]) => key !== 'id' && key !== 'fields' && val !== undefined)
      .map(([key, val]) => `  ${key}: ${printValue(val)},`);
    const hasFields = (schema.fields?.length ?? 0) > 0;
    const fieldsBlock = schema.fields ? `  fields: [\n${printFields(schema.fields, byId)}\n  ],` : '';
    const body = `export const ${schema.id} = defineSchema({\n  id: ${quote(schema.id)},\n${[...headProps, fieldsBlock].filter(Boolean).join('\n')}\n});\n`;
    const schemaImport = hasFields ? 'defineField, defineSchema' : 'defineSchema';
    files.set(
      `${toKebabCase(schema.id)}.ts`,
      [PULL_MARKER, `import { ${schemaImport} } from '@localess/schema';`, ...importLines, '', body].join('\n')
    );
  }

  const names = schemas.map(schema => schema.id);
  const indexImports = schemas.map(schema => `import { ${schema.id} } from './${toKebabCase(schema.id)}';`);
  files.set(
    'index.ts',
    [
      PULL_MARKER,
      `import { defineConfig } from '@localess/schema';`,
      ...indexImports,
      '',
      `export const config = defineConfig({\n  schemas: [${names.join(', ')}],\n});\n`,
    ].join('\n')
  );
  return files;
}
