import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import process from 'node:process';

import { Command } from 'commander';

import { localessCliClient } from '../../../client';
import { LocalessApiError } from '../../../models';
import { getSession } from '../../../session';
import { DEFAULT_PRINT_WIDTH, emitSchemaFiles, PULL_MARKER } from './emitter';

type PullOptions = {
  path: string;
  printWidth: number;
  verbose?: boolean;
};

export const schemaPullCommand = new Command('pull')
  .description('Generate TypeScript schema definitions from your Localess space')
  .option('-p, --path <path>', 'Directory to write schema definition files into', 'schemas')
  .option(
    '--print-width <n>',
    'Column width before a defineField(...) call wraps to one property per line — match your own .prettierrc',
    value => parseInt(value, 10),
    DEFAULT_PRINT_WIDTH
  )
  .option('-v, --verbose', 'Print verbose debug output')
  .action(async (options: PullOptions) => {
    const session = await getSession();
    if (!session.isLoggedIn) {
      console.error('Not logged in');
      console.error('Please log in first using "localess login" command');
      process.exit(1);
      return;
    }
    const client = localessCliClient({
      origin: session.origin,
      spaceId: session.space,
      token: session.token,
      ...(options.verbose ? { debug: true } : {}),
    });
    try {
      console.log('Fetching schemas from Localess...');
      const schemas = await client.getSchemas();
      const files = emitSchemaFiles(schemas, options.printWidth);
      const dir = resolve(process.cwd(), options.path);
      mkdirSync(dir, { recursive: true });
      const skipped: string[] = [];
      // delete previously pulled files whose schema no longer exists
      for (const existing of readdirSync(dir).filter(name => name.endsWith('.ts'))) {
        const content = readFileSync(join(dir, existing), 'utf8');
        if (content.startsWith(PULL_MARKER)) {
          if (!files.has(existing)) {
            rmSync(join(dir, existing));
            console.log(`Deleted ${existing} (schema no longer on server)`);
          }
        } else if (files.has(existing)) {
          skipped.push(existing);
        }
      }
      for (const [name, content] of files) {
        if (skipped.includes(name)) continue;
        writeFileSync(join(dir, name), content);
      }
      if (skipped.length > 0) {
        console.warn(`Skipped ${skipped.join(', ')}: not generated by pull (missing marker). Rename or remove to let pull own them.`);
      }
      console.log(`Wrote ${files.size - skipped.length} files to ${dir} (${schemas.length} schemas)`);
    } catch (error) {
      if (!(error instanceof LocalessApiError)) {
        console.error('Failed to pull schemas:', error);
      }
      process.exit(1);
    }
  });
