// Generated by `localess schema pull`. Do not edit — the next pull overwrites this file.
import { defineEnum } from '@localess/schema';

export const ButtonType = defineEnum({
  id: 'ButtonType',
  displayName: 'Button Type',
  description: 'It will define the visual part of a button.',
  labels: ['button'],
  values: [
    { name: 'Primary', value: 'primary' },
    { name: 'Secondary', value: 'secondary' },
  ],
});
