// Generated by `localess schema pull`. Do not edit — the next pull overwrites this file.
import { defineConfig } from '@localess/schema';
import { Button } from './button';
import { ButtonType } from './button-type';
import { Page } from './page';
import { Section } from './section';

export const config = defineConfig({
  schemas: [Button, ButtonType, Page, Section],
});
