// Generated by `localess schema pull`. Do not edit — the next pull overwrites this file.
import { defineSchema } from '@localess/schema';

export const Section = defineSchema({
  id: 'Section',
  type: 'NODE',
  displayName: 'Section',
});
