import {SchemaComponent, SchemaEnum, SchemaFieldKind, SchemaType, Schemas, SchemaField} from '../../../models';

const PREAMBLE = `// Generated by Localess CLI - do not edit manually

export interface ContentAsset {
  kind: 'ASSET';
  uri: string;
}

export interface ContentLink {
  kind: 'LINK';
  target: '_blank' | '_self';
  type: 'url' | 'content';
  uri: string;
}

export interface ContentReference {
  kind: 'REFERENCE';
  uri: string;
}

export interface ContentRichText {
  type?: string;
  content?: ContentRichText[];
}
`;

export function toPascalCase(str: string): string {
  return str
    .replace(/[-_\s]+([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase())
    .replace(/^[a-z]/, c => c.toUpperCase());
}

function fieldToTsType(field: SchemaField): string {
  switch (field.kind) {
    case SchemaFieldKind.TEXT:
    case SchemaFieldKind.TEXTAREA:
    case SchemaFieldKind.MARKDOWN:
    case SchemaFieldKind.COLOR:
    case SchemaFieldKind.DATE:
    case SchemaFieldKind.DATETIME:
      return 'string';
    case SchemaFieldKind.NUMBER:
      return 'number';
    case SchemaFieldKind.BOOLEAN:
      return 'boolean';
    case SchemaFieldKind.RICH_TEXT:
      return 'ContentRichText';
    case SchemaFieldKind.LINK:
      return 'ContentLink';
    case SchemaFieldKind.ASSET:
      return 'ContentAsset';
    case SchemaFieldKind.ASSETS:
      return 'ContentAsset[]';
    case SchemaFieldKind.REFERENCE:
      return 'ContentReference';
    case SchemaFieldKind.REFERENCES:
      return 'ContentReference[]';
    case SchemaFieldKind.OPTION:
      return field.source ? toPascalCase(field.source) : 'string';
    case SchemaFieldKind.OPTIONS:
      return field.source ? `${toPascalCase(field.source)}[]` : 'string[]';
    case SchemaFieldKind.SCHEMA: {
      const refs = field.schemas;
      if (!refs || refs.length === 0) return 'unknown';
      const types = refs.map(s => toPascalCase(s));
      return types.length === 1 ? types[0] : types.join(' | ');
    }
    case SchemaFieldKind.SCHEMAS: {
      const refs = field.schemas;
      if (!refs || refs.length === 0) return 'unknown[]';
      const types = refs.map(s => toPascalCase(s));
      const union = types.length === 1 ? types[0] : `(${types.join(' | ')})`;
      return `${union}[]`;
    }
  }
}

export function generateTypes(schemas: Schemas): string {
  const parts: string[] = [PREAMBLE];
  const rootTypeNames: string[] = [];

  for (const [key, schema] of Object.entries(schemas)) {
    const typeName = toPascalCase(key);

    if (schema.type === SchemaType.ENUM) {
      const enumSchema = schema as SchemaEnum;
      const values = enumSchema.values ?? [];
      if (values.length === 0) {
        parts.push(`export type ${typeName} = string;\n`);
      } else {
        const union = values.map(v => `'${v.value}'`).join(' | ');
        parts.push(`export type ${typeName} = ${union};\n`);
      }
    } else {
      const component = schema as SchemaComponent;
      if (schema.type === SchemaType.ROOT) {
        rootTypeNames.push(typeName);
      }

      const fieldLines = (component.fields ?? []).map(field => {
        const tsType = fieldToTsType(field);
        const opt = field.required ? '' : '?';
        return `  ${field.name}${opt}: ${tsType};`;
      });

      parts.push(`export interface ${typeName} {\n${fieldLines.join('\n')}\n}\n`);
    }
  }

  if (rootTypeNames.length > 0) {
    parts.push(`export type ContentData = ${rootTypeNames.join(' | ')};\n`);
  } else {
    parts.push('export type ContentData = unknown;\n');
  }

  return parts.join('\n');
}
