import {SchemaComponent, SchemaEnum, SchemaFieldKind, SchemaType, Schemas, SchemaField} from '../../../models';

function getPreamble(prefix: string): string {
  return `/**
 * Generated by Localess CLI
 * Do not edit manually.
 */

/**
 * Content Asset define reference to a Asset.
 */
export interface ${prefix}ContentAsset {
  /** Define the type of Asset */
  kind: 'ASSET';
  /** Unique identifier for the asset. */
  uri: string;
}

/**
 * Content Link define reference to a Link.
 */
export interface ${prefix}ContentLink {
  /** Define the type of Link */
  kind: 'LINK';
  /** Define the target of the link. _blank for new tab and _self for same tab. */
  target: '_blank' | '_self';
  /** Define the type of Link. URL for external links and Content for internal links. */
  type: 'url' | 'content';
  /** If type is content, then it will be Content ID. Otherwise it will be URL. */
  uri: string;
}

/**
 * Content Reference define reference to a Content.
 */
export interface ${prefix}ContentReference {
  /** Define the type of Reference */
  kind: 'REFERENCE';
  /** Unique identifier for the Content Document. */
  uri: string;
}

/**
 * Content RichText define content as JSON Object.
 */
export interface ${prefix}ContentRichText {
  /** Define the type of Content Node */
  type?: string;
  /** List of Content Nodes */
  content?: ${prefix}ContentRichText[];
}
`;
}

export function toPascalCase(str: string): string {
  return str
    .replace(/[-_\s]+([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase())
    .replace(/^[a-z]/, c => c.toUpperCase());
}

function fieldToTsType(field: SchemaField, prefix: string): string {
  switch (field.kind) {
    case SchemaFieldKind.TEXT:
    case SchemaFieldKind.TEXTAREA:
    case SchemaFieldKind.MARKDOWN:
    case SchemaFieldKind.COLOR:
    case SchemaFieldKind.DATE:
    case SchemaFieldKind.DATETIME:
      return 'string';
    case SchemaFieldKind.NUMBER:
      return 'number';
    case SchemaFieldKind.BOOLEAN:
      return 'boolean';
    case SchemaFieldKind.RICH_TEXT:
      return `${prefix}ContentRichText`;
    case SchemaFieldKind.LINK:
      return `${prefix}ContentLink`;
    case SchemaFieldKind.ASSET:
      return `${prefix}ContentAsset`;
    case SchemaFieldKind.ASSETS:
      return `${prefix}ContentAsset[]`;
    case SchemaFieldKind.REFERENCE:
      return `${prefix}ContentReference`;
    case SchemaFieldKind.REFERENCES:
      return `${prefix}ContentReference[]`;
    case SchemaFieldKind.OPTION:
      return field.source ? prefix + toPascalCase(field.source) : 'string';
    case SchemaFieldKind.OPTIONS:
      return field.source ? `${prefix + toPascalCase(field.source)}[]` : 'string[]';
    case SchemaFieldKind.SCHEMA: {
      const refs = field.schemas;
      if (!refs || refs.length === 0) return 'unknown';
      const types = refs.map(s => prefix + toPascalCase(s));
      return types.length === 1 ? types[0] : types.join(' | ');
    }
    case SchemaFieldKind.SCHEMAS: {
      const refs = field.schemas;
      if (!refs || refs.length === 0) return 'unknown[]';
      const types = refs.map(s => prefix + toPascalCase(s));
      const union = types.length === 1 ? types[0] : `(${types.join(' | ')})`;
      return `${union}[]`;
    }
  }
}

function toJsDoc(description: string, indent = ''): string {
  return `${indent}/**\n${indent} * ${description}\n${indent} */`;
}

export function generateTypes(schemas: Schemas, prefix = ''): string {
  const parts: string[] = [getPreamble(prefix)];
  const rootTypeNames: string[] = [];

  for (const [key, schema] of Object.entries(schemas)) {
    const typeName = prefix + toPascalCase(key);
    const typeDoc = schema.description ? `${toJsDoc(schema.description)}\n` : '';

    if (schema.type === SchemaType.ENUM) {
      const enumSchema = schema as SchemaEnum;
      const values = enumSchema.values ?? [];
      if (values.length === 0) {
        parts.push(`${typeDoc}export type ${typeName} = string;\n`);
      } else {
        const union = values.map(v => `'${v.value}'`).join(' | ');
        parts.push(`${typeDoc}export type ${typeName} = ${union};\n`);
      }
    } else {
      const component = schema as SchemaComponent;
      if (schema.type === SchemaType.ROOT) {
        rootTypeNames.push(typeName);
      }

      const fieldLines = [
        `  /** Unique identifier of a component in a content. */`,
        `  _id: string;`,
        `  /** Unique identifier for the Schema object. */`,
        `  _schema: '${key}';`,
        ...(component.fields ?? []).slice().sort((a, b) => a.name.localeCompare(b.name)).flatMap(field => {
          const tsType = fieldToTsType(field, prefix);
          const opt = field.required ? '' : '?';
          const lines: string[] = [];
          if (field.description) {
            lines.push(`  /** ${field.description} */`);
          }
          lines.push(`  ${field.name}${opt}: ${tsType};`);
          return lines;
        }),
      ];

      parts.push(`${typeDoc}export interface ${typeName} {\n${fieldLines.join('\n')}\n}\n`);
    }
  }

  parts.push(`/**\n* ContentData defined Object to connect all possible root Schemas.\n*/`);
  if (rootTypeNames.length > 0) {
    parts.push(`export type ${prefix}ContentData = ${rootTypeNames.join(' | ')};\n`);
  } else {
    parts.push(`export type ${prefix}ContentData = unknown;\n`);
  }

  return parts.join('\n');
}
