import { createApp } from 'vue';
import { Localess } from '@localess/vue';
import App from './App.vue';
import { router } from './router';
// @ts-expect-error -- generated by @localess/vue/vite's localess() plugin at build time
import { localessComponents } from 'virtual:localess-vue-components';

const app = createApp(App);
app.use(router);
app.use(Localess, {
  origin: import.meta.env.VITE_LOCALESS_ORIGIN,
  spaceId: import.meta.env.VITE_LOCALESS_SPACE_ID,
  token: import.meta.env.VITE_LOCALESS_TOKEN,
  components: localessComponents,
  enableSync: true,
});
app.mount('#app');
