<script lang="ts">
  import { getLocaless, localessInit, LocalessComponent } from '@localess/svelte';
  // @ts-expect-error -- generated by @localess/svelte/vite's localess() plugin at build time
  import { localessComponents } from 'virtual:localess-svelte-components';

  localessInit({
    origin: import.meta.env.VITE_LOCALESS_ORIGIN,
    spaceId: import.meta.env.VITE_LOCALESS_SPACE_ID,
    token: import.meta.env.VITE_LOCALESS_TOKEN,
    components: localessComponents,
    enableSync: true,
  });

  let slug = $state(window.location.pathname.replace(/^\//, '') || 'home');
  let content = $state<any>(undefined);

  getLocaless()
    .getContentBySlug(slug)
    .then(result => (content = result));
</script>

{#if content}
  <LocalessComponent data={content.data} />
{:else}
  <p>Loading…</p>
{/if}
