/**
 * Ambient module declarations for the virtual modules generated by
 * `localess()` (`vitePluginLocalessInit`/`vitePluginLocalessComponents`).
 *
 * Published as its own subpath, `@localess/react/vite/virtual-modules`, because a type-only
 * `.d.ts` isn't reachable through `@localess/react/vite`'s regular `import`/`export` graph — the
 * dts bundler only follows those, not triple-slash references, so this can't be pulled in
 * automatically. Add it to your tsconfig the same way you already add `vite/client`:
 *
 * ```json
 * { "compilerOptions": { "types": ["vite/client", "@localess/react/vite/virtual-modules"] } }
 * ```
 *
 * Without this, a bare `import 'virtual:localess-init'` (the documented usage — see
 * `docs/react.md`) fails to resolve under `tsc`, surfacing as a hard error on any tsconfig with
 * `noUncheckedSideEffectImports: true`.
 */
declare module 'virtual:localess-init' {}

/**
 * Internal-only — generated code inside `vitePluginLocalessComponents` imports this module, but
 * that code is emitted as a raw JS string at build time (see
 * `generateComponentsModuleCode`), never type-checked by `tsc` directly. No consumer-facing code
 * imports this module, so it's declared empty rather than typed, to avoid publishing a shape
 * that isn't exercised (or verified) anywhere.
 */
declare module 'virtual:localess-components' {}
