import { Localess } from '@localess/vue';

import { defineNuxtPlugin, useRuntimeConfig } from '#app';
// @ts-expect-error generated by the module at build time
import { localessComponents } from '#build/localess-components.mjs';

import type { PublicModuleOptions } from '../types';

/**
 * Installs `@localess/vue`'s plugin with the **public** half of the module
 * options, so `useLocaless()` and the components work in the browser exactly as
 * they do in plain Vue.
 *
 * The secret `serverToken` is deliberately not read here — it lives in
 * `runtimeConfig.localess`, which Nuxt never serialises into the client bundle.
 * Server-side fetching goes through `useLocalessServerClient()` instead.
 */
export default defineNuxtPlugin(nuxtApp => {
  const localess = useRuntimeConfig().public.localess as PublicModuleOptions;

  if (!localess?.token) return;

  nuxtApp.vueApp.use(Localess, {
    origin: localess.origin,
    spaceId: localess.spaceId,
    token: localess.token,
    debug: localess.debug,
    enableSync: localess.enableSync,
    components: localessComponents,
  });
});
