/**
 * Generated by Localess CLI
 * Do not edit manually.
 */

/**
 * Content Asset define reference to a Asset.
 */
export interface ContentAsset {
  /** Define the type of Asset */
  kind: 'ASSET';
  /** Unique identifier for the asset. */
  uri: string;
}

/**
 * Content Link define reference to a Link.
 */
export interface ContentLink {
  /** Define the type of Link */
  kind: 'LINK';
  /** Define the target of the link. _blank for new tab and _self for same tab. */
  target: '_blank' | '_self';
  /** Define the type of Link. URL for external links and Content for internal links. */
  type: 'url' | 'content';
  /** If type is content, then it will be Content ID. Otherwise it will be URL. */
  uri: string;
}

/**
 * Content Reference define reference to a Content.
 */
export interface ContentReference {
  /** Define the type of Reference */
  kind: 'REFERENCE';
  /** Unique identifier for the Content Document. */
  uri: string;
}

/**
 * Content RichText define content as JSON Object.
 */
export interface ContentRichText {
  /** Define the type of Content Node */
  type?: string;
  /** List of Content Nodes */
  content?: ContentRichText[];
}

export interface Button {
  /** Unique identifier of a component in a content. */
  _id: string;
  /** Unique identifier for the Schema object. */
  _schema: 'Button';
  label: string;
  type: ButtonType;
}

export type ButtonType = 'primary' | 'secondary';

export interface Page {
  /** Unique identifier of a component in a content. */
  _id: string;
  /** Unique identifier for the Schema object. */
  _schema: 'Page';
  buttons?: Button[];
  /** Rich Text example */
  content?: ContentRichText;
  description?: string;
  title?: string;
}

export interface Section {
  /** Unique identifier of a component in a content. */
  _id: string;
  /** Unique identifier for the Schema object. */
  _schema: 'Section';
}

/**
* ContentData defined Object to connect all possible root Schemas.
*/
export type ContentData = Page;
